### ISSUE TITLE
Dragonfly Failed to decode recognition

### ISSUE THREAD

**Issue by LexiconCode** [dictation-toolbox/dragonfly#242] opened 2020-04-21 19:21 UTC
This happens when the engine successfully recognizes a grammar rule, but Dragonfly couldn't find which rule was recognised. I have personally experienced this issue once. However I have at least 2 to 3 people that experience 100% with fresh installs with commands utilizing a dictation element.

Users are experiencing this with other commands but here is an example:
`gum bow <some words> brunt`

User reports command debug statement suggests `some words` is being treated by dragonfly as a commands.
- `('gum', 0), ('bow', 0), ('some', 0), ('words', 0), ('brunt', 0)] `
The expected debugging should look like the following where `some words` recognized as free dictation.
- `("some", 0), ("words", 0) would be ("some", 1000000), ("words", 1000000), ('brunt', 0)] ` `
- I verified that `some words` is not a command elsewhere. 

Suspect debug sample
```
DEBUG:engine:Grammar ccr-1: received recognition [('gum', 0), ('bow', 0), ('some', 0), ('words', 0), ('brunt', 0)].
DEBUG:grammar.decode:   attempt: RepeatRule(Repeater1)
DEBUG:grammar.decode:    -- Decoding State: ' >> gum bow some words brunt'
DEBUG:grammar.decode:      attempt: Compound(u'[<original> original] [<caster_base_sequence>] [terminal <terminal>]')
DEBUG:grammar.decode:         attempt: Sequence(...)
.
.
.
DEBUG:grammar.decode:                                    attempt: Alternative(...)
DEBUG:grammar.decode:                                       attempt: Sequence(...)
DEBUG:grammar.decode:                                          attempt: Choice(..., name='capitalization')
DEBUG:grammar.decode:                                             attempt: Compound(u'cop')
DEBUG:grammar.decode:                                                attempt: Literal([u'cop'])
DEBUG:grammar.decode:                                                failure: Literal([u'cop'])
DEBUG:grammar.decode:                                             rollback: Compound(u'cop')
.
.
.
```

- These are known good debug logs for comparison without the reported issue.
The three files are debug logs with the following configurations: Vanilla is the formatting command unaltered, Modified is the version, Modified version with Test Engine.

All the logs begin with an utterance and end with execution of the command in DNS.
[Text-formatting-commands---modified---test-engine.txt](https://github.com/dictation-toolbox/dragonfly/files/4512113/Text-formatting-commands---modified---test-engine.txt)
[Text-formatting-commands---modified.txt](https://github.com/dictation-toolbox/dragonfly/files/4512114/Text-formatting-commands---modified.txt)
[Text-formatting-commands---vanilla.txt](https://github.com/dictation-toolbox/dragonfly/files/4512115/Text-formatting-commands---vanilla.txt)

Other commands is being reproduced with `say hello how are you` should produce `hello how are you` instead `failed to decode recognition (u'say', u'hello', u'how', u'are', u'you')`

Ultimately those values are passed by Natlink to the results callbacks of grammar objects. Could there be a bug in Natlink returning the wrong values or something else along those lines.

**Comment by LexiconCode** [comment] 2020-04-22 17:54
All right thanks to @tlappas we have a few more details.

- A complete debug log of the command failing not truncated.
[debug-decode-error.txt](https://github.com/dictation-toolbox/dragonfly/files/4518031/debug-decode-error.txt)
- The issue occurs regardless if it's a `mappingrule` or of CCR `mergerule` which utilize dragonfly repetition. This should rule out dragonfly's repetition optimization from causing the issue.
- The decoding error this only occurs when Natlink `runs out of process`. Waiting for a second user to confirm.

**Comment by Danesprite** [comment] 2020-04-23 07:55
Thanks for putting this together @LexiconCode! :+1:

I have been trying to figure out if this is a bug with Natlink or Dragonfly. So far, I can't find anything obvious that could be causing this. Natlink's code for results just forwards the rule integer value (`dwCFGParse`) given by Dragon to the results callbacks of grammars. It doesn't change it, neither does Dragonfly's code.

The only possibilities I see here are:
1) this is a Dragon bug that only occurs for some people; or
2) these words are somehow being passed along with the grammar.

For case two, I put together some code that constructs the set of all command words in loaded grammars. It might be of some use.

```Python
from dragonfly import get_engine
from dragonfly.grammar.elements_basic import Literal, ListBase

all_commands = set()
for grammar in get_engine().grammars:
    commands = set()
    for rule in grammar.rules:
        for element in grammar._get_element_list(rule):
            if isinstance(element, Literal):
                commands.add(" ".join(element.words))
            elif isinstance(element, ListBase):
                commands.extend(element.list.get_list_items())
        all_commands.update(commands)

    print("Grammar {!r} has {} unique command phrases.".format(grammar.name,
                                                               len(commands)))

print("Total unique command phrases: {}.".format(len(all_commands)))
print("Command phrases include {!r}: {}".format("some words",
                                                "some words" in all_commands))

```

**Comment by Danesprite** [comment] 2020-07-12 08:51
I'm going to partially fix this by checking recognised words against a set of the grammar and list words. That should fix the problem for most cases.

Ideally, the parser should be rewritten, but doing so would be quite difficult and time-consuming. Repetition elements and CCR make this a difficult problem to solve efficiently.

**Comment by Danesprite** [comment] 2020-07-12 11:45
This will be mostly fixed in release version 0.25.0.

I have removed the `NatLink` label because this is a quirk or bug with Dragon. Ryan Hileman has kindly [confirmed this](https://gitter.im/dictation-toolbox/natlink?at=5ea1f429afa1f51d4e172f11) for us on Gitter.

**Closed** 2020-07-22 08:52 UTC
Labels: Bug, Dragon NaturallySpeaking

**Comment by LexiconCode** [comment] 2026-03-20 14:49
Natlink ISRResGraphW.GetWordNode → SRRESWORDNODE.dwCFGParse, which gives authoritative rule IDs directly from the graph might be a way to fix the issue. Obviously This isn't the solution but it's an interesting thought that we could rebuild the graph instead of relying on getResults.

```py
import ctypes
import struct

# Maximum word buffer: 140 WCHAR
_SRWORDW_BUF_SIZE = 280


def get_results_via_graph(res_basic, tlb, choice=0):
    """Get recognized words with correct rule IDs from the result graph.

    Args:
        res_basic: ISRResBasicW interface (from QI on the result IUnknown).
        tlb:       comtypes-generated type library module with
                   ISRResGraphW, IDgnSRResGraphW, SRRESWORDNODE,
                   DGNSRRESWORDNODE structs.
        choice:    Recognition choice index (0 = best).

    Returns:
        List of {"word": str, "cfg_parse": int} dicts, where cfg_parse
        is the grammar rule ID that matched each word.

    Raises:
        COMError: If BestPathWord or GetWordNode fails.
    """
    graph = res_basic.QueryInterface(tlb.ISRResGraphW)

    # --- BestPathWord: get the ordered list of word-node IDs -------
    # "We preallocate 512 words for the best path and hope the grammar
    # does not include something larger."
    path_buf = (ctypes.c_ulong * 512)()
    needed = ctypes.c_ulong(0)
    hr = graph._ISRResGraphW__com_BestPathWord(
        choice, path_buf, ctypes.sizeof(path_buf), ctypes.byref(needed))
    if hr < 0:
        raise ctypes.WinError(hr)
    count = needed.value // 4  # needed is bytes, not count

    # --- GetWordNode: retrieve each node's word text + rule ID -----
    # Prefer IDgnSRResGraphW (Dragon extension with DGNSRRESWORDNODE)
    # which has extra timing fields.  Fall back to ISRResGraphW.
    try:
        gwn = res_basic.QueryInterface(tlb.IDgnSRResGraphW)
        use_dgn = True
    except Exception:
        gwn = graph
        use_dgn = False

    results = []
    for i in range(count):
        node_id = path_buf[i]
        word_buf = (ctypes.c_ubyte * _SRWORDW_BUF_SIZE)()
        word_needed = ctypes.c_ulong(0)

        if use_dgn:
            node = tlb.DGNSRRESWORDNODE()
            hr = gwn._IDgnSRResGraphW__com_GetWordNode(
                node_id, ctypes.byref(node), word_buf,
                _SRWORDW_BUF_SIZE, ctypes.byref(word_needed))
        else:
            node = tlb.SRRESWORDNODE()
            hr = gwn._ISRResGraphW__com_GetWordNode(
                node_id, ctypes.byref(node), word_buf,
                _SRWORDW_BUF_SIZE, ctypes.byref(word_needed))

        if hr < 0:
            continue

        word_text = _parse_srwordw(bytes(word_buf))
        if word_text:
            results.append({
                "word": word_text,
                "cfg_parse": node.dwCFGParse,  # <-- the reliable rule ID
            })

    return results


def _parse_srwordw(word_bytes):
    """Extract word text from an SRWORDW byte buffer.

    SRWORDW layout:
        DWORD dwSize;      // total entry size in bytes
        DWORD dwWordNum;   // <-- unreliable, do not use for rule IDs
        WCHAR szWord[];    // null-terminated UTF-16LE text
    """
    if len(word_bytes) < 10:
        return ""
    entry_size = struct.unpack_from("<I", word_bytes, 0)[0]
    text_data = word_bytes[8:min(entry_size, len(word_bytes))]
    try:
        return text_data.decode("utf-16-le").rstrip("\x00")
    except UnicodeDecodeError:
        return ""


# --- Minimal usage example -----------------------------------------

if __name__ == "__main__":
    print(__doc__)
    print("This module is meant to be imported, not run directly.")
    print()
    print("Usage:")
    print("  from rule_id_fix import get_results_via_graph")
    print("  words = get_results_via_graph(res_basic, tlb, choice=0)")
    print("  for w in words:")
    print('      print(f"{w[\'word\']} -> rule {w[\'cfg_parse\']}")')
```

**Comment by drmfinlay** [comment] 2026-03-21 01:33
This is basically what `CResultsObject` already does, minus using the Dragon version of `SRRESWORDNODE`.  Best to patch Natlink instead, if this does get us the right rule numbers.

There are actually some minor problems with my approach.  They are related to rule importing and the special exposed rules "dgnwords" and "dgnletters".  Probably fixable.
