### ISSUE TITLE
Unknown Char because of wrong keyboard layout

### ISSUE THREAD

**Issue by MatthijsBurgh** [dictation-toolbox/dragonfly#114] opened 2019-08-10 07:23 UTC
When importing dragonfly, I get the following message:
```
ERROR:typeables:Unknown char: 'a'
ERROR:typeables:Unknown char: 'a'
ERROR:typeables:Unknown char: 'b'
ERROR:typeables:Unknown char: 'b'
ERROR:typeables:Unknown char: 'c'
ERROR:typeables:Unknown char: 'c'
ERROR:typeables:Unknown char: 'd'
ERROR:typeables:Unknown char: 'd'
ERROR:typeables:Unknown char: 'e'
ERROR:typeables:Unknown char: 'e'
ERROR:typeables:Unknown char: 'f'
ERROR:typeables:Unknown char: 'f'
ERROR:typeables:Unknown char: 'g'
ERROR:typeables:Unknown char: 'g'
ERROR:typeables:Unknown char: 'h'
ERROR:typeables:Unknown char: 'h'
ERROR:typeables:Unknown char: 'i'
ERROR:typeables:Unknown char: 'i'
ERROR:typeables:Unknown char: 'j'
ERROR:typeables:Unknown char: 'j'
ERROR:typeables:Unknown char: 'k'
ERROR:typeables:Unknown char: 'k'
ERROR:typeables:Unknown char: 'l'
ERROR:typeables:Unknown char: 'l'
ERROR:typeables:Unknown char: 'm'
ERROR:typeables:Unknown char: 'm'
ERROR:typeables:Unknown char: 'n'
ERROR:typeables:Unknown char: 'n'
ERROR:typeables:Unknown char: 'o'
ERROR:typeables:Unknown char: 'o'
ERROR:typeables:Unknown char: 'p'
ERROR:typeables:Unknown char: 'p'
ERROR:typeables:Unknown char: 'q'
ERROR:typeables:Unknown char: 'q'
ERROR:typeables:Unknown char: 'r'
ERROR:typeables:Unknown char: 'r'
ERROR:typeables:Unknown char: 's'
ERROR:typeables:Unknown char: 's'
ERROR:typeables:Unknown char: 't'
ERROR:typeables:Unknown char: 't'
ERROR:typeables:Unknown char: 'u'
ERROR:typeables:Unknown char: 'u'
ERROR:typeables:Unknown char: 'v'
ERROR:typeables:Unknown char: 'v'
ERROR:typeables:Unknown char: 'w'
ERROR:typeables:Unknown char: 'w'
ERROR:typeables:Unknown char: 'x'
ERROR:typeables:Unknown char: 'x'
ERROR:typeables:Unknown char: 'y'
ERROR:typeables:Unknown char: 'y'
ERROR:typeables:Unknown char: 'z'
ERROR:typeables:Unknown char: 'z'
ERROR:typeables:Unknown char: 'A'
ERROR:typeables:Unknown char: 'A'
ERROR:typeables:Unknown char: 'B'
ERROR:typeables:Unknown char: 'B'
ERROR:typeables:Unknown char: 'C'
ERROR:typeables:Unknown char: 'C'
ERROR:typeables:Unknown char: 'D'
ERROR:typeables:Unknown char: 'D'
ERROR:typeables:Unknown char: 'E'
ERROR:typeables:Unknown char: 'E'
ERROR:typeables:Unknown char: 'F'
ERROR:typeables:Unknown char: 'F'
ERROR:typeables:Unknown char: 'G'
ERROR:typeables:Unknown char: 'G'
ERROR:typeables:Unknown char: 'H'
ERROR:typeables:Unknown char: 'H'
ERROR:typeables:Unknown char: 'I'
ERROR:typeables:Unknown char: 'I'
ERROR:typeables:Unknown char: 'J'
ERROR:typeables:Unknown char: 'J'
ERROR:typeables:Unknown char: 'K'
ERROR:typeables:Unknown char: 'K'
ERROR:typeables:Unknown char: 'L'
ERROR:typeables:Unknown char: 'L'
ERROR:typeables:Unknown char: 'M'
ERROR:typeables:Unknown char: 'M'
ERROR:typeables:Unknown char: 'N'
ERROR:typeables:Unknown char: 'N'
ERROR:typeables:Unknown char: 'O'
ERROR:typeables:Unknown char: 'O'
ERROR:typeables:Unknown char: 'P'
ERROR:typeables:Unknown char: 'P'
ERROR:typeables:Unknown char: 'Q'
ERROR:typeables:Unknown char: 'Q'
ERROR:typeables:Unknown char: 'R'
ERROR:typeables:Unknown char: 'R'
ERROR:typeables:Unknown char: 'S'
ERROR:typeables:Unknown char: 'S'
ERROR:typeables:Unknown char: 'T'
ERROR:typeables:Unknown char: 'T'
ERROR:typeables:Unknown char: 'U'
ERROR:typeables:Unknown char: 'U'
ERROR:typeables:Unknown char: 'V'
ERROR:typeables:Unknown char: 'V'
ERROR:typeables:Unknown char: 'W'
ERROR:typeables:Unknown char: 'W'
ERROR:typeables:Unknown char: 'X'
ERROR:typeables:Unknown char: 'X'
ERROR:typeables:Unknown char: 'Y'
ERROR:typeables:Unknown char: 'Y'
ERROR:typeables:Unknown char: 'Z'
ERROR:typeables:Unknown char: 'Z'
ERROR:typeables:Unknown char: '0'
ERROR:typeables:Unknown char: '0'
ERROR:typeables:Unknown char: '1'
ERROR:typeables:Unknown char: '1'
ERROR:typeables:Unknown char: '2'
ERROR:typeables:Unknown char: '2'
ERROR:typeables:Unknown char: '3'
ERROR:typeables:Unknown char: '3'
ERROR:typeables:Unknown char: '4'
ERROR:typeables:Unknown char: '4'
ERROR:typeables:Unknown char: '5'
ERROR:typeables:Unknown char: '5'
ERROR:typeables:Unknown char: '6'
ERROR:typeables:Unknown char: '6'
ERROR:typeables:Unknown char: '7'
ERROR:typeables:Unknown char: '7'
ERROR:typeables:Unknown char: '8'
ERROR:typeables:Unknown char: '8'
ERROR:typeables:Unknown char: '9'
ERROR:typeables:Unknown char: '9'
ERROR:typeables:Unknown char: '!'
ERROR:typeables:Unknown char: '!'
ERROR:typeables:Unknown char: '!'
ERROR:typeables:Unknown char: '@'
ERROR:typeables:Unknown char: '@'
ERROR:typeables:Unknown char: '#'
ERROR:typeables:Unknown char: '#'
ERROR:typeables:Unknown char: '$'
ERROR:typeables:Unknown char: '$'
ERROR:typeables:Unknown char: '%'
ERROR:typeables:Unknown char: '%'
ERROR:typeables:Unknown char: '^'
ERROR:typeables:Unknown char: '^'
ERROR:typeables:Unknown char: '&'
ERROR:typeables:Unknown char: '&'
ERROR:typeables:Unknown char: '&'
ERROR:typeables:Unknown char: '*'
ERROR:typeables:Unknown char: '*'
ERROR:typeables:Unknown char: '*'
ERROR:typeables:Unknown char: '('
ERROR:typeables:Unknown char: '('
ERROR:typeables:Unknown char: '('
ERROR:typeables:Unknown char: ')'
ERROR:typeables:Unknown char: ')'
ERROR:typeables:Unknown char: ')'
ERROR:typeables:Unknown char: '-'
ERROR:typeables:Unknown char: '-'
ERROR:typeables:Unknown char: '-'
ERROR:typeables:Unknown char: '_'
ERROR:typeables:Unknown char: '_'
ERROR:typeables:Unknown char: '+'
ERROR:typeables:Unknown char: '+'
ERROR:typeables:Unknown char: '`'
ERROR:typeables:Unknown char: '`'
ERROR:typeables:Unknown char: '~'
ERROR:typeables:Unknown char: '~'
ERROR:typeables:Unknown char: '['
ERROR:typeables:Unknown char: '['
ERROR:typeables:Unknown char: '['
ERROR:typeables:Unknown char: ']'
ERROR:typeables:Unknown char: ']'
ERROR:typeables:Unknown char: ']'
ERROR:typeables:Unknown char: '{'
ERROR:typeables:Unknown char: '{'
ERROR:typeables:Unknown char: '{'
ERROR:typeables:Unknown char: '}'
ERROR:typeables:Unknown char: '}'
ERROR:typeables:Unknown char: '}'
ERROR:typeables:Unknown char: '\\'
ERROR:typeables:Unknown char: '\\'
ERROR:typeables:Unknown char: '|'
ERROR:typeables:Unknown char: '|'
ERROR:typeables:Unknown char: ':'
ERROR:typeables:Unknown char: ':'
ERROR:typeables:Unknown char: ';'
ERROR:typeables:Unknown char: ';'
ERROR:typeables:Unknown char: "'"
ERROR:typeables:Unknown char: "'"
ERROR:typeables:Unknown char: "'"
ERROR:typeables:Unknown char: "'"
ERROR:typeables:Unknown char: '"'
ERROR:typeables:Unknown char: '"'
ERROR:typeables:Unknown char: '"'
ERROR:typeables:Unknown char: '"'
ERROR:typeables:Unknown char: ','
ERROR:typeables:Unknown char: ','
ERROR:typeables:Unknown char: '.'
ERROR:typeables:Unknown char: '.'
ERROR:typeables:Unknown char: '/'
ERROR:typeables:Unknown char: '/'
ERROR:typeables:Unknown char: '<'
ERROR:typeables:Unknown char: '<'
ERROR:typeables:Unknown char: '<'
ERROR:typeables:Unknown char: '<'
ERROR:typeables:Unknown char: '>'
ERROR:typeables:Unknown char: '>'
ERROR:typeables:Unknown char: '>'
ERROR:typeables:Unknown char: '>'
ERROR:typeables:Unknown char: '?'
ERROR:typeables:Unknown char: '?'
ERROR:typeables:Unknown char: '='
ERROR:typeables:Unknown char: '='
ERROR:typeables:Unknown char: '='
Falling back to Shift+insert for Paste's action.
```

I have tracked down that `layout = windll.user32.GetKeyboardLayout(0)` either returns `0` or ` -268368887`. I have tried this on two windows 10 machines. One actual machine, one virtualbox. The host of the virtualbox is not the same machine as "the actual machine".

I have found that it happens on US English, US International Keyboard. When using US keyboard and opening a new CMD window, the issue doesn't occur.

I know this is outside of this library, but are you familiar with this issue?

**Comment by Danesprite** [comment] 2019-08-11 11:13
Thank you for opening this issue. I am aware of this problem generally, although this many unknown character errors is unusual for an English layout.

The problem is complicated, but put simply it occurs because dragonfly doesn't use the keyboard layout of the current foreground window when typing keys. Virtualised or no, the errors will occur on any modern version of Windows, although I understand there are some differences in Windows 8 and above.

I already have a mostly working solution for fixing this, I just haven't gotten around to publishing it yet. I'll make a PR for it shortly. I hope to remove unknown character errors altogether by falling back on dragonfly's support for typing Unicode characters.

**Comment by Danesprite** [comment] 2019-11-23 00:00
@MatthijsBurgh Just an FYI, this should be fixed on `master` now. I will be releasing a new dragonfly2 version this weekend. Sorry it took so long to fix!

**Comment by MatthijsBurgh** [comment] 2019-11-23 08:46
Thanks for the heads up.

**Comment by Danesprite** [comment] 2019-11-26 14:26
No worries!

All done now. Releasing version 0.19.0 took a bit longer than expected. You should be able to upgrade using pip.

**Closed by Danesprite** 2019-11-26 14:26 UTC
Labels: Bug, Windows
